server:
  listen_address: 127.0.0.1:2222
  host_keys: null 
logging:
  file: null 
  json: false 
  timestamps: true 
  debug: false 
auth:
  no_auth: false 
  max_tries: 0 
  password_auth:
    enabled: true 
    accepted: true 
  public_key_auth:
    enabled: true 
    accepted: false
ssh_proto:
  version: SSH-2.0-gossh-honey
  banner: A simple ssh honey pot, fake ssh server that lets anyone to connect and monitor their activty